### ISSUE TITLE
Is IceDB licensed under an open source license?

### ISSUE THREAD

**Issue by akesling** [danthegoodman1/icedb#128]
IceDB looks interesting, but I can't seem to find any licensing information.

@danthegoodman1, would you consider adding a LICENSE file to the root of the repository to clarify this?  Even if it's just an explicit copyright statement, it would be helpful to _know_ what the intended IP restrictions are.

If you're unsure what license to use and just want it to be open/available, I'm a fan of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

**Comment by danthegoodman1** [comment]
Just added a temporary one. If you want to use it for something in particular please reach out!
